language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-19
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
  licenses:
    - android-sdk-license-.+
    - google-gdk-license-.+

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - chmod +x gradlew
  - adb shell input keyevent 82 &

script:
  - "./gradlew clean build --stacktrace"
